baseURL = "https://hariteja.dev/"
title = "Hari Teja Tatavarti"
theme = "latex-minimal"
languageCode = "en"
defaultContentLanguage = "en"

[pagination]
  pagerSize = 10

[params]
  author = "Hari Teja Tatavarti"
  description = "AI Scientist & Engineer | Thinking Human"
  keywords = "AI,Machine Learning,GPU,CUDA,Deep Learning"
  info = "AI Scientist & Engineer"

  avatarURL = ""
  gravatar = ""

  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2025

  enableTwemoji = false

  colorScheme = "light"
  hideColorSchemeToggle = false

  customCSS = []
  customSCSS = ["scss/custom.scss"]
  customJS = []

[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github"
  weight = 1
  url = "https://github.com/c0derzer0"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin"
  weight = 2
  url = "https://linkedin.com/in/hari-teja-at-linkedn"

[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope"
  weight = 3
  url = "mailto:contactme.teja@gmail.com"

[menu]
  [[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

  [[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts/"

  [[menu.main]]
    name = "Projects"
    weight = 3
    url = "projects/"

  [[menu.main]]
    name = "Publications"
    weight = 4
    url = "publications/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"